/*
  Register definitions for slave core: Timing Receiver Core registers

  * File           : wb_tim_rcv_core_regs.h
  * Author         : auto-generated by wbgen2 from tim_rcv_core.wb
  * Created        : Mon Aug 28 13:38:10 2017
  * Standard       : ANSI C

    THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE tim_rcv_core.wb
    DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!

*/

#ifndef __WBGEN2_REGDEFS_TIM_RCV_CORE_WB
#define __WBGEN2_REGDEFS_TIM_RCV_CORE_WB

#include <inttypes.h>

#if defined( __GNUC__)
#define PACKED __attribute__ ((packed))
#else
#error "Unsupported compiler?"
#endif

#ifndef __WBGEN2_MACROS_DEFINED__
#define __WBGEN2_MACROS_DEFINED__
#define WBGEN2_GEN_MASK(offset, size) (((1<<(size))-1) << (offset))
#define WBGEN2_GEN_WRITE(value, offset, size) (((value) & ((1<<(size))-1)) << (offset))
#define WBGEN2_GEN_READ(reg, offset, size) (((reg) >> (offset)) & ((1<<(size))-1))
#define WBGEN2_SIGN_EXTEND(value, bits) (((value) & (1<<bits) ? ~((1<<(bits))-1): 0 ) | (value))
#endif


/* definitions for register: Phase Measurement Control register */

/* definitions for register: DMTD A Control register */

/* definitions for field: Deglitcher Threshold in reg: DMTD A Control register */
#define TIM_RCV_CORE_DMTD_A_CTL_DEGLITCHER_THRES_MASK WBGEN2_GEN_MASK(0, 16)
#define TIM_RCV_CORE_DMTD_A_CTL_DEGLITCHER_THRES_SHIFT 0
#define TIM_RCV_CORE_DMTD_A_CTL_DEGLITCHER_THRES_W(value) WBGEN2_GEN_WRITE(value, 0, 16)
#define TIM_RCV_CORE_DMTD_A_CTL_DEGLITCHER_THRES_R(reg) WBGEN2_GEN_READ(reg, 0, 16)

/* definitions for field: Reserved1 in reg: DMTD A Control register */
#define TIM_RCV_CORE_DMTD_A_CTL_RESERVED1_MASK WBGEN2_GEN_MASK(16, 16)
#define TIM_RCV_CORE_DMTD_A_CTL_RESERVED1_SHIFT 16
#define TIM_RCV_CORE_DMTD_A_CTL_RESERVED1_W(value) WBGEN2_GEN_WRITE(value, 16, 16)
#define TIM_RCV_CORE_DMTD_A_CTL_RESERVED1_R(reg) WBGEN2_GEN_READ(reg, 16, 16)

/* definitions for register: DMTD B Control register */

/* definitions for field: Deglitcher Threshold in reg: DMTD B Control register */
#define TIM_RCV_CORE_DMTD_B_CTL_DEGLITCHER_THRES_MASK WBGEN2_GEN_MASK(0, 16)
#define TIM_RCV_CORE_DMTD_B_CTL_DEGLITCHER_THRES_SHIFT 0
#define TIM_RCV_CORE_DMTD_B_CTL_DEGLITCHER_THRES_W(value) WBGEN2_GEN_WRITE(value, 0, 16)
#define TIM_RCV_CORE_DMTD_B_CTL_DEGLITCHER_THRES_R(reg) WBGEN2_GEN_READ(reg, 0, 16)

/* definitions for field: Reserved1 in reg: DMTD B Control register */
#define TIM_RCV_CORE_DMTD_B_CTL_RESERVED1_MASK WBGEN2_GEN_MASK(16, 16)
#define TIM_RCV_CORE_DMTD_B_CTL_RESERVED1_SHIFT 16
#define TIM_RCV_CORE_DMTD_B_CTL_RESERVED1_W(value) WBGEN2_GEN_WRITE(value, 16, 16)
#define TIM_RCV_CORE_DMTD_B_CTL_RESERVED1_R(reg) WBGEN2_GEN_READ(reg, 16, 16)

/* definitions for register: Averaged Phase Difference Measurement */

/* definitions for register: DMTD A input clock Frequency */

/* definitions for field: Frequency in reg: DMTD A input clock Frequency */
#define TIM_RCV_CORE_F_DMTD_A_FREQ_MASK       WBGEN2_GEN_MASK(0, 28)
#define TIM_RCV_CORE_F_DMTD_A_FREQ_SHIFT      0
#define TIM_RCV_CORE_F_DMTD_A_FREQ_W(value)   WBGEN2_GEN_WRITE(value, 0, 28)
#define TIM_RCV_CORE_F_DMTD_A_FREQ_R(reg)     WBGEN2_GEN_READ(reg, 0, 28)

/* definitions for field: Valid in reg: DMTD A input clock Frequency */
#define TIM_RCV_CORE_F_DMTD_A_VALID           WBGEN2_GEN_MASK(28, 1)

/* definitions for register: DMTD B input clock Frequency */

/* definitions for field: Frequency in reg: DMTD B input clock Frequency */
#define TIM_RCV_CORE_F_DMTD_B_FREQ_MASK       WBGEN2_GEN_MASK(0, 28)
#define TIM_RCV_CORE_F_DMTD_B_FREQ_SHIFT      0
#define TIM_RCV_CORE_F_DMTD_B_FREQ_W(value)   WBGEN2_GEN_WRITE(value, 0, 28)
#define TIM_RCV_CORE_F_DMTD_B_FREQ_R(reg)     WBGEN2_GEN_READ(reg, 0, 28)

/* definitions for field: Valid in reg: DMTD B input clock Frequency */
#define TIM_RCV_CORE_F_DMTD_B_VALID           WBGEN2_GEN_MASK(28, 1)
/* [0x0]: REG Phase Measurement Control register */
#define TIM_RCV_CORE_REG_PHASE_MEAS_NAVG 0x00000000
/* [0x4]: REG DMTD A Control register */
#define TIM_RCV_CORE_REG_DMTD_A_CTL 0x00000004
/* [0x8]: REG DMTD B Control register */
#define TIM_RCV_CORE_REG_DMTD_B_CTL 0x00000008
/* [0xc]: REG Averaged Phase Difference Measurement */
#define TIM_RCV_CORE_REG_PHASE_MEAS 0x0000000c
/* [0x10]: REG DMTD A input clock Frequency */
#define TIM_RCV_CORE_REG_F_DMTD_A 0x00000010
/* [0x14]: REG DMTD B input clock Frequency */
#define TIM_RCV_CORE_REG_F_DMTD_B 0x00000014
#endif
